# Copyright 2010  The "go-linoise" Authors
#
# Use of this source code is governed by the Simplified BSD License
# that can be found in the LICENSE file.
#
# This software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied. See the License
# for more details.

include $(GOROOT)/src/Make.inc

TARG=github.com/kless/go-linoise/linoise
GOFILES=\
	buffer.go\
	error.go\
	history.go\
	linoise.go\
	question.go\
	util.go\
#	quest.go\

include $(GOROOT)/src/Make.pkg

